baseURL: https://marta-wnek.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: About me
    subtitle: |-
      Passionate to decipher the future of businesses with use of Data Analytics.
      
      As Sir Churchill said: 
      > The farther back you can look, the farther
      forward you can see.
      
    title: Hi, my name is Marta
  blog: {}
  contact:
    address:
      - city: London, ST 00000
        country: United Kingdom
        street: Lisson Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: martawnek24@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: "7493403401"
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
     #   label: Twitter
      #  url: https://www.twitter.com
    #  - icon: fa-facebook
      #  label: Facebook
       # url: https://www.facebook.com
      #- icon: fa-instagram
       # label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/marta-wnek
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/marta-wnek/
  image: ''
  name: Your name
  navigation:
    #button1:
    #  - name: Contact
      #  url: '#'/address
   # button2:
    #  - name: Log In
     #   url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/
      - name: My projects
        url: projects/
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: me.jpg
        subtitle: Me in a nutshell
        title: CV
        url: blogs/aliquam
      - image: pic05.jpg
        subtitle: How I got into Analytics
        title: My journey
        url: blogs/bempus
        buttonMe:
        - name: Read my story
          url: blogs/bempus    
      - image: pic10.jpg
        subtitle: Climate Change and Anomalies
        title: Ecosystem
        url: projects/ipsum
      - image: pic09.jpg
        subtitle: Political Affiliation on Brexit Voting
        title: Politics
        url: projects/magna
      - image: pic03.jpg
        subtitle: Renewable Energy Production
        title: Energy
        url: projects/zliquam
     # - image: pic06.jpg
      #  subtitle: Feugiat Amet Tempus
       # title: Etiam
        #url: blogs/ipsum
 # two:
   # buttonText: 
   # enable: yes
  #  subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
   #   \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
    #  condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
     # pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
    #  Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
     # amet pharetra et feugiat tempus."
  #  title: Massa libe
  #  url: blogs
