---
categories:
- ""
- ""
date: "2017-10-31T21:28:43-05:00"
description: ""
draft: false
image: pic10.jpg
keywords: ""
slug: ipsum
title: Climate change and anomalies
---



<p>The following <strong><em>layout settings</em></strong> are made:</p>
<p>The following <strong><em>packages</em></strong> are installed in RStudio:</p>
<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined
Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the
Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space
Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of
temperature anomalies can be found
here</a></p>
<p>To define temperature anomalies I need to have a reference, or base, period which NASA clearly states that it is the period between
1951-1980.</p>
<p>I ran the code below to load the file:</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<p><strong>NOTE:</strong> When using this function, I added two options: <code>skip</code> and
<code>na</code>:</p>
<ol style="list-style-type: decimal">
<li><p><strong><em>The <code>skip=1</code></em></strong> option is there as the real data table only starts in Row 2, so I need to skip one row.</p></li>
<li><p><strong><em><code>na = "***"</code></em></strong> option informs R how missing observations in the spreadsheet are coded. When looking at the spreadsheet, you can see that missing data is coded as “***”. It is good practice to specify this here, as otherwise some of the data is not recognized as numeric data.</p></li>
<li><p>Once the data is loaded, there is an <strong><em>object titled <code>weather</code>
in the <code>Environment</code> panel</em></strong>.</p></li>
</ol>
<p><strong>Side note</strong>: If you cannot see the panel (usually on the
top-right), go to <code>Tools</code> &gt; <code>Global Options</code> &gt; <code>Pane Layout</code> and tick the checkbox next to <code>Environment</code>. Click on the <code>weather</code> object, and the dataframe will pop up on a seperate tab. Inspect the dataframe.</p>
<p>For each month and year, the dataframe shows the deviation of
temperature from the normal (expected). Further, the dataframe is in wide format.</p>
</div>
<div id="cleaning-the-data" class="section level1">
<h1>Cleaning the data</h1>
<p>First, I cleaned the data to leave only the relevant ones for the analysis:</p>
<ul>
<li><p>Selected the year and the twelve month variables from the <code>weather</code> dataset.</p></li>
<li><p>Converted the dataframe from wide to ‘long’ format, and named the new dataframe as <code>tidyweather</code>, the variable containing the name of the month as <code>month</code>, and the temperature deviation values as <code>delta</code>.</p></li>
</ul>
<pre class="r"><code># Create tidyweather data
tidyweather &lt;- weather %&gt;% 
  select(-c(&quot;J-D&quot;, &quot;D-N&quot;, &quot;DJF&quot;, &quot;JJA&quot;, &quot;MAM&quot;, &quot;SON&quot;)) %&gt;% 
  pivot_longer(cols = -Year, names_to = &quot;month&quot;, values_to = &quot;delta&quot;)</code></pre>
<ul>
<li>Then, I inspected this dataframe to have three variables now, one each for:
<ul>
<li>year,</li>
<li>month, and</li>
<li>delta, or temperature deviation.</li>
</ul></li>
</ul>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>For the purpose of the analysis, I needed to plot the data using a time-series scatter plot, and add a trendline.</p>
<p><em>To do that, I first needed to create a new variable called <code>date</code> in order to ensure that the <code>delta</code> values are plot chronologically.</em></p>
<p><strong>NOTE:</strong>
&gt; In the following chunk of code, I used the <code>eval=FALSE</code> argument, which does not run a chunk of code;</p>
<blockquote>
<p>I did so that I can knit the document before tidying the data and creating a new dataframe<code>tidyweather</code>.</p>
</blockquote>
<blockquote>
<p>To actually run this code and knit this document, <code>eval=FALSE</code> must be deleted, <strong>not just here but in all chunks were <code>eval=FALSE</code> appears.</strong></p>
</blockquote>
<pre class="r"><code># Set date format tidyweather data
tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

# Plot weather anomalies
ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;
  )</code></pre>
<p><img src="/projects/project3_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>To verify if the effect of increasing temperature is more pronounced in some months, I used <code>facet_wrap()</code> to produce a separate scatter plot for each month, again with a smoothing line.</p>
<p><img src="/projects/project3_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="conclusion-1" class="section level1">
<h1>Conclusion 1:</h1>
<p>Based on the plots, it can be implied that the effect of increasing temperature is more pronounced in the winter months - starting from the end of fall until the start of spring. I can see this from the higher values within the winter months over the other months across time. <strong>This reflects the effects of global warming/climate change throughout the last decade.</strong></p>
<p><strong>NOTE:</strong>
- It is sometimes useful to group data into different time periods to study historical data. <em>For example, we often refer to decades such as 1970s, 1980s, 1990s etc. to refer to a period of time.</em>
&gt; Here, NASA calculates a temperature anomaly, as a difference from the base period of 1951-1980.</p>
<p>With the code below I:
- Created a new data frame called <code>comparison</code> that groups data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present.
- Removed data before 1800 and before using <code>filter</code>.
- Used the <code>mutate</code> function to create a new variable <code>interval</code> which contains information on which period each observation belongs to.
- Assigned the different periods using <code>case_when()</code>.</p>
<pre class="r"><code># Assign periods
comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Next:
- Inspected the <code>comparison</code> data frame by clicking on it in the
<code>Environment</code> pane.</p>
<ul>
<li><p>Now, that I have the <code>interval</code> variable, I could create a <strong><em>density plot</em></strong> <em>to study the distribution of monthly deviations</em> (<code>delta</code>), <em>grouped by the different time periods</em> we are interested in.</p></li>
<li><p>Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p></li>
</ul>
<pre class="r"><code># Create density plot of monthly deviation based off each interval period
ggplot(comparison, aes(delta, fill = interval, alpha = 0.1)) +
  geom_density() +
  labs(title = &quot;Denisty plots of monthly deviations&quot;, subtitle = &quot;Separated by Intervals&quot;, x = &quot;Delta&quot;, y = &quot;Density&quot;) +
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10)
)</code></pre>
<p><img src="/projects/project3_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="conclusion-2" class="section level1 underline">
<h1>Conclusion 2:</h1>
<p>From 1881 until 1980, I did not observe huge anomalies in terms of
temperature delta from the base period (1951-1980). However, this was not reflected past 1980; temperatures began rising more drastically from 1981-present. More strikingly, the average delta for the last period is around 0.5 higher than that of the previous period (1981-2010). <em>This hints at even higher average deviations in future that come faster unless a downward pressure is exerted on temperature increases through climate change measures.</em></p>
<p>So far, I have been working with monthly anomalies. However, we might be interested in average annual anomalies. I did this by using:
- <code>group_by()</code> and <code>summarise()</code>, followed by
- a scatter plot to display the result.</p>
<pre class="r"><code># Create yearly averages
average_annual_anomaly &lt;- comparison %&gt;%
  group_by(Year) %&gt;% 
  summarise(mean_delta_year = mean(delta))

# plot mean annual delta across years:
ggplot(average_annual_anomaly, aes(x = Year, y= mean_delta_year)) +
  geom_point() +
  geom_smooth(colour = &quot;red&quot;, method = &quot;loess&quot;) +
  theme_bw() +
  labs (
    title = &quot;Yearly Weather Anomalies&quot;,
    y = &quot;Mean annual delta&quot;
  )</code></pre>
<p><img src="/projects/project3_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Fit the best fit line, using LOESS method
#change theme to theme_bw() to have white background + black frame around plot</code></pre>
</div>
<div id="conclusion-3" class="section level1 underline">
<h1>Conclusion 3:</h1>
<p>Like what I was hinting at earlier, <strong>the yearly anomalies over the past four decades (starting from 1980) have followed a relatively exponential upward trend</strong>. During the 1980s, the average yearly delta was between 0 and 0.5 whereas this average has climbed past 1.5 in the most recent years. This increase of 1 degree overall has not been witnessed in the century prior to 1980, thus <strong>emphasising the magnitude of the rapidly worsening global warming phenomenon.</strong></p>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their
website</a>
that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast
amount of heat to warm all the oceans, atmosphere, and land by that
much. In the past, a one- to two-degree drop was all it took to plunge
the Earth into the Little Ice Age.</p>
</blockquote>
<p>Here, I constructed a confidence interval for the average annual delta since 2011, both using a formula and using a bootstrap simulation with the <code>infer</code> package.</p>
<p><strong>NOTE:</strong>
<strong>Recall that the dataframe <code>comparison</code> has already grouped temperature anomalies according to time intervals;</strong> =&gt; we are only interested in what is happening between 2011-present.</p>
<pre class="r"><code># Formula method of CI calculation
formula_ci &lt;- comparison %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;%
  drop_na() %&gt;% 
  summarise(mean_delta = mean(delta),
                     sd_delta = sd(delta),
                     count = n(),
                     t_critical = qt(0.975, count-1),
                     se_delta = sd_delta / sqrt(count),
                     margin_of_error = t_critical * se_delta,
                     delta_low  = mean_delta - margin_of_error,
                     delta_high  = mean_delta + margin_of_error
            )
# Print out formula_CI
formula_ci</code></pre>
<pre><code>## # A tibble: 1 × 8
##   mean_delta sd_delta count t_critical se_delta margin_of_error delta_…¹ delta…²
##        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1       1.07    0.265   140       1.98   0.0224          0.0443     1.02    1.11
## # … with abbreviated variable names ¹​delta_low, ²​delta_high</code></pre>
<pre class="r"><code>library(infer)
# Bootstrap method of CI calculation using Infer package
infer_bootstrap_ci &lt;- comparison %&gt;%
  filter(interval == &quot;2011-present&quot;) %&gt;%
  specify(response = delta) %&gt;%
  generate(reps = 1000,  type = &quot;bootstrap&quot;) %&gt;% 
  calculate(stat = &quot;mean&quot;, na.rm = TRUE) %&gt;% 
  get_confidence_interval(level = .95)
# Print out bootstrap CI using Infer package
infer_bootstrap_ci</code></pre>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.02     1.11</code></pre>
</div>
</div>
<div id="conclusion-4" class="section level1 underline">
<h1>Conclusion 4:</h1>
<p>The results give an interesting insight into the sea and land
temperature differences during the 2011 - present time interval. The mean of the temperature delta is around 1.06 degrees. By means of a confidence interval calculation I can <strong>state with 95% certainty that the mean temperature delta is between 1.02 and 1.11 degrees for this time period</strong>. As there is no underlying distribution, I used the t-statistics and a degrees of freedom of n-1 to calculate the critical values required for a confidence interval calculation.</p>
<p>I confirmed this estimate by using a bootstrapping method that manually created the confidence intervals and provided a lower bound of 1.02 degrees and a upper bound of 1.11 degrees.</p>
</div>
